package com.example.mungala;

import java.util.UUID;

public interface Constants {
    int BLUETOOTH_ENABLE_REQUEST = 0;
    int BLUETOOTH_DISCOVERABLE_REQUEST = 1;
    int FIND_DEVICE_REQUEST = 2;
    int SETUP_SINGLE_PLAYER_GAME_REQUEST = 3;
    int BLUETOOTH_MULTIPLAYER_GAME_REQUEST = 4;

    int ACCESS_COARSE_LOCATION_PERMISSION_REQUEST = 0;

    UUID MY_UUID = UUID.fromString("00001101-0000-1000-8000-00805F9B34FB");

    String MY_TAG = "XTAG";

    int CONNECTION_ESTABLISHED_CONNECT = 0;
    int CONNECTION_LOST = 1;
    int CONNECTION_FAILED = 2;
    int DATA_RECEIVED = 3;
    int DATA_SENT = 4;
    int CONNECTION_ESTABLISHED_HOST= 5;

    String EXTRA_DEVICE_ADDRESS = BuildConfig.APPLICATION_ID + ".EXTRA_DEVICE_ADDRESS";
    String EXTRA_HAS_FIRST_TURN = BuildConfig.APPLICATION_ID + ".EXTRA_HAS_FIRST_TURN";
    //String EXTRA_BLUETOOTH_SERVICE = BuildConfig.APPLICATION_ID + ".EXTRA_BLUETOOTH_SOCKET";
    String EXTRA_DIFFICULTY_LEVEL = BuildConfig.APPLICATION_ID + ".EXTRA_DIFFICULTY_LEVEL";

    byte MOVE_READY_SIGNAL = 10;
    byte MOVE_ACCEPT_SIGNAL = 11;
    byte MOVE_ACCEPT_SIGNAL_2 = 12;
    byte INVALID_MOVE = 15;
    byte NO_CONNECTION = 16;
    //byte BACK_READY_SGINAL = 17;
    //byte BACK_ACCEPT_SIGNAL = 18;


}
